name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make -C Cloud_Computing_Foundations install
    - name: Lint with pylint
      run: |
        make -C Cloud_Computing_Foundations lint
    - name: Test with pytest
      run: |
        make -C Cloud_Computing_Foundations test
    - name: Format code
      run: |
        make -C Cloud_Computing_Foundations format
