name: Github Actions with Sequenced Jobs

on: [push]

jobs:
  
  # Define the name of the job
  test-job-1:
    # Define the operating system to run the application on
    runs-on: ubuntu-latest
    
    # Specific the steps in the job
    steps:
      # Utilising a predefined marketplace GitHub Actions 
      
      # help pull the code from the repo to the runner
      - uses: actions/checkout@v3
      # Installs python in the virtual machine
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
              
              # Specify the Terminal command to run the Python Script
      - run: python3 CodeWithPrince_Tutorial/my_script.py

  test-job-2:
    # Define the operating system to run the application on
    runs-on: ubuntu-latest
    needs: [test-job-1]
    # Specific the steps in the job
    steps:
      # Utilising a predefined marketplace GitHub Actions 
      
      # help pull the code from the repo to the runner
      - uses: actions/checkout@v3
      # Installs python in the virtual machine
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
              
              # Specify the Terminal command to run the Python Script
      - run: python3 CodeWithPrince_Tutorial/my_script.py